version: "3"
services:

    #frontend: Vue JS web app
    #kanopole-front:
    #    container_name: kanopole-front
    #    image: kanopole-vue:1.0
    #    depends_on:
    #        - kanopole-api
    #    links:
    #        - kanopole-api:kanopole-api
    #    ports:
    #        - 58080:8080
    #    volumes:
    #        - ./kanopole-front/code:/app
    #    environment:
    #        - API_URL=http://localhost:53000/
    #    networks:
    #        - kanopole
    #    tty: true
    #    restart: on-failure:10

    #backend: HapiJS REST API
    kanopole-api:
        container_name: kanopole-api
        image: kanopole-api:1.0
        depends_on:
            - kanopole-db
        ports:
            - 53000:3000
        volumes:
            - ./kanopole-api/code:/api
        environment:
            - DATABASE_URL=kanopole-db
        networks:
            - kanopole
        tty: true
        restart: on-failure:10

    #database: mongo
    kanopole-db:
        container_name: kanopole-db
        image: mongo
        ports: 
            - 52717:27017
        volumes:
            - ./kanopole-db/db:/nest-api/db
        networks:
            - kanopole


networks:
    kanopole:
        driver: bridge
